<cfscript>

qoptions = { result="result", datasource="recipes"};

settings = {
    "folder": "c:\temp\",
    "files": {
        "thumbnails_to_do": "thumbnails_to_do.txt",
        "done_list": "done_list.txt",
        "files_list": "files.txt",
        "folders_list": "folders.txt",
        "magick_to_do": "magick_to_do.bat",
        "mkdir_to_do": "mk_dir_to_do.bat",
        "server_file_list": "server_files.txt"
    },
    "drive": "I:"
};
</cfscript>